# Generated by Django 4.2.5 on 2023-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_thing_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='thing',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
